# Generated by Django 5.0.6 on 2024-05-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_rename_full_name_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
