# Generated by Django 5.0.6 on 2024-05-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
