# Generated by Django 5.0.6 on 2024-05-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_alter_blogpost_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
