# Generated by Django 5.0.6 on 2024-05-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_alter_blogpost_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
