# Generated by Django 5.0.6 on 2024-05-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0011_customuser_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
